# Generated by Django 5.0.2 on 2024-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cpforcnpj', models.CharField(max_length=18, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('farm_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('total_area_hectares', models.FloatField()),
                ('arable_area_hectares', models.IntegerField()),
                ('vegetation_area_hectares', models.IntegerField()),
                ('planted_types', models.CharField(max_length=200)),
            ],
        ),
    ]
